name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    tags:
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack src/ChangeCurator.CLI/ChangeCurator.CLI.csproj --output packages --configuration Release
    - uses: actions/upload-artifact@v2
      with:
        name: ChangeCurator.CLI
        path: packages/ChangeCurator.CLI*.nupkg
    - name: Push
      if: contains(github.ref, 'release')
      run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json
